import { Component } from '@angular/core';
import { CardVideoComponent } from '../../shared/card-video/card-video.component';
import { IVides } from '../../../types/tempData';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CardVideoComponent],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css',
})
export class DashboardComponent {
  allData: IVides[] = [
    {
      id: 1,
      imgUrl: 'assets/images/thumbnails/thumbnail1.jpg',
      title: 'Understanding JavaScript in 10 Minutes',
      time: '3:42',
      timestamp: '2 days ago',
      views: '5K',
      uploader: 'Coding Ninja',
    },
    {
      id: 2,
      imgUrl: 'assets/images/thumbnails/thumbnail2.jpg',
      title: 'Learn Python the Easy Way Today',
      time: '2:58',
      timestamp: '1 week ago',
      views: '15K',
      uploader: 'Tech Guru',
    },
    {
      id: 3,
      imgUrl: 'assets/images/thumbnails/thumbnail3.jpg',
      title: 'Top 10 JavaScript Frameworks to Know',
      time: '4:23',
      timestamp: '3 months ago',
      views: '1M',
      uploader: 'Web Dev Simplified',
    },
    {
      id: 4,
      imgUrl: 'assets/images/thumbnails/thumbnail4.jpg',
      title: 'Mastering Data Structures in Python',
      time: '4:27',
      timestamp: '6 hours ago',
      views: '2K',
      uploader: 'Code Academy',
    },
    {
      id: 5,
      imgUrl: 'assets/images/thumbnails/thumbnail5.jpg',
      title: 'The Ultimate Guide to React Components',
      time: '3:12',
      timestamp: '4 days ago',
      views: '50K',
      uploader: 'React Ninja',
    },
    {
      id: 6,
      imgUrl: 'assets/images/thumbnails/thumbnail6.jpg',
      title: 'Become a Full Stack Developer Today',
      time: '18:20',
      timestamp: '2 months ago',
      views: '500K',
      uploader: 'Developer Hub',
    },
    {
      id: 7,
      imgUrl: 'assets/images/thumbnails/thumbnail7.jpg',
      title: 'Understanding the Basics of Git and GitHub',
      time: '7:01',
      timestamp: '3 days ago',
      views: '30K',
      uploader: 'Version Control',
    },
    {
      id: 8,
      imgUrl: 'assets/images/thumbnails/thumbnail8.jpg',
      title: 'Creating Stunning Websites with HTML and CSS',
      time: '8:58',
      timestamp: '1 day ago',
      views: '20K',
      uploader: 'Web Design Pro',
    },
    {
      id: 9,
      imgUrl: 'assets/images/thumbnails/thumbnail1.jpg',
      title: 'Advanced JavaScript Techniques for Experts',
      time: '1:02',
      timestamp: '5 hours ago',
      views: '10K',
      uploader: 'JS Mastery',
    },
    {
      id: 10,
      imgUrl: 'assets/images/thumbnails/thumbnail2.jpg',
      title: 'Top 5 Tips for Effective Coding Practices',
      time: '5:22',
      timestamp: '1 month ago',
      views: '80K',
      uploader: 'Code Guru',
    },
    {
      id: 11,
      imgUrl: 'assets/images/thumbnails/thumbnail7.jpg',
      title: 'Understanding JavaScript in 10 Minutes',
      time: '3:42',
      timestamp: '2 days ago',
      views: '5K',
      uploader: 'Coding Ninja',
    },
    {
      id: 12,
      imgUrl: 'assets/images/thumbnails/thumbnail6.jpg',
      title: 'Learn Python the Easy Way Today',
      time: '2:58',
      timestamp: '1 week ago',
      views: '15K',
      uploader: 'Tech Guru',
    },
    {
      id: 13,
      imgUrl: 'assets/images/thumbnails/thumbnail3.jpg',
      title: 'Top 10 JavaScript Frameworks to Know',
      time: '4:23',
      timestamp: '3 months ago',
      views: '1M',
      uploader: 'Web Dev Simplified',
    },
    {
      id: 14,
      imgUrl: 'assets/images/thumbnails/thumbnail4.jpg',
      title: 'Mastering Data Structures in Python',
      time: '4:27',
      timestamp: '6 hours ago',
      views: '2K',
      uploader: 'Code Academy',
    },
    {
      id: 15,
      imgUrl: 'assets/images/thumbnails/thumbnail5.jpg',
      title: 'The Ultimate Guide to React Components',
      time: '3:12',
      timestamp: '4 days ago',
      views: '50K',
      uploader: 'React Ninja',
    },
    {
      id: 16,
      imgUrl: 'assets/images/thumbnails/thumbnail6.jpg',
      title: 'Become a Full Stack Developer Today',
      time: '18:20',
      timestamp: '2 months ago',
      views: '500K',
      uploader: 'Developer Hub',
    },
    {
      id: 17,
      imgUrl: 'assets/images/thumbnails/thumbnail7.jpg',
      title: 'Understanding the Basics of Git and GitHub',
      time: '7:01',
      timestamp: '3 days ago',
      views: '30K',
      uploader: 'Version Control',
    },
    {
      id: 18,
      imgUrl: 'assets/images/thumbnails/thumbnail8.jpg',
      title: 'Creating Stunning Websites with HTML and CSS',
      time: '8:58',
      timestamp: '1 day ago',
      views: '20K',
      uploader: 'Web Design Pro',
    },
    {
      id: 19,
      imgUrl: 'assets/images/thumbnails/thumbnail1.jpg',
      title: 'Advanced JavaScript Techniques for Experts',
      time: '1:02',
      timestamp: '5 hours ago',
      views: '10K',
      uploader: 'JS Mastery',
    },
    {
      id: 20,
      imgUrl: 'assets/images/thumbnails/thumbnail2.jpg',
      title: 'Top 5 Tips for Effective Coding Practices',
      time: '5:22',
      timestamp: '1 month ago',
      views: '80K',
      uploader: 'Code Guru',
    },
  ];
}
